In [1]:
import tensorflow as tf
import numpy as np
import random
import matplotlib.pyplot as plt

from numpy import genfromtxt


# Load in training and testing data
# Shape of (record_num, col_num): (999,7)

my_data = genfromtxt('Data/s10_s23_train_datab.csv', delimiter=',')
my_testing = genfromtxt('Data/s10_s23_test_datab.csv', delimiter=',')
my_real = genfromtxt('Data/s10_s23_test_datab.csv', delimiter=',')


category = 1

factor = 5


In [9]:


# batch function
def my_batch(category,num,my_data):
#     choose a num of batch return x, y as vectors
    size,col = my_data.shape
    idList = random.sample(range(0, size), num )
    batch_xs = np.zeros(shape=(num,col-category))
    batch_ys = np.zeros(shape=(num,category))
    
    for index,i in enumerate(idList):
        line = my_data[i,:-category]
        batch_xs[index]=line
        label = my_data[i,col-category:col]
        batch_ys[index]=label
    return batch_xs,batch_ys
    
def testingDataLoader(category,my_data):
    size,col = my_data.shape
    
    batch_xs = np.zeros(shape=(size,col-category))
    batch_ys = np.zeros(shape=(size,category))
    for index,line in enumerate(my_data):
        batch_xs[index]=line[:-category]
        batch_ys[index]=line[col-category:col]

        
    return batch_xs,batch_ys

# get real data
def realDataLoader(category,my_data):
    size,col = my_data.shape
    batch_xs = np.zeros(shape=(size,col-category))
    for index,line in enumerate(my_data):
        batch_xs[index]=line[:-category]
    print size,col-category
    return batch_xs


In [42]:
# Implementation starts!

num_hidden = 256

# None means any number, so x is not a specific number here.
x = tf.placeholder(tf.float32, [None, factor],name="x-input")


# Init weights, bias, (all zeros first) and define softmax function
W = tf.Variable(tf.zeros([factor, category]),name="weights")
b = tf.Variable(tf.zeros([category],name="bias"))


# Variables.
layer1_weights = tf.Variable(tf.truncated_normal(
      [factor, num_hidden], stddev=0.1))
layer1_biases = tf.Variable(tf.zeros([num_hidden]))

layer2_weights = tf.Variable(tf.truncated_normal(
      [num_hidden,category], stddev=0.1))
layer2_biases = tf.Variable(tf.zeros([category]))

# dropout
keep_prob = tf.placeholder("float")



# use a name scope to organize nodes in the graph visualizer
with tf.name_scope("Wx_b") as scope:
# ------------------------------------------------------------------------------------------------------------------
# first multiply x and w, then add b vector. apply softmax to get probabilities
#   y = tf.nn.softmax(tf.matmul(x, W) + b)
#     y = tf.matmul(x, W) + b
    
    hidden = tf.matmul(x,layer1_weights)+layer1_biases
    
#     hidden = tf.nn.softmax(hidden)

# dropout
    hidden = tf.nn.dropout(hidden, keep_prob)

    y = tf.matmul(hidden,layer2_weights)+layer2_biases
    
    
    
    
print "y",type(y)

# Add summary ops to collect data
w_hist = tf.histogram_summary("weights", W)
b_hist = tf.histogram_summary("biases", b)
y_hist = tf.histogram_summary("y", y)


weights_summary = tf.histogram_summary("weights", W)
biases_summary = tf.histogram_summary("biases", b)
y_summary = tf.histogram_summary("y", y)



# Out put
y_ = tf.placeholder(tf.float32, [None, category],name="y-input")

with tf.name_scope("xent") as scope:
# ------------------------------------------------------------------------------------------------------------------
# tf.log computes logarithm of each element. Cost Function.
#   cross_entropy = -tf.reduce_sum(y_*tf.log(y))
    gap = tf.sub(y,y_)
    cross_entropy = tf.reduce_sum(tf.abs(gap))
    
with tf.name_scope("train") as scope:
# minimize cross_entropy using the gradient descent algorithm with a learning rate of 0.01. 
  train_step = tf.train.GradientDescentOptimizer(0.0001).minimize(cross_entropy)

# # Learning rate decay
#   global_step = tf.Variable(0, trainable=False)
#   starter_learning_rate = 0.001
#   learning_rate = tf.train.exponential_decay(starter_learning_rate, global_step,
#                                            100000, 0.96, staircase=True)
#   train_step = tf.train.GradientDescentOptimizer(learning_rate).minimize(cross_entropy)



  
init = tf.initialize_all_variables()

# launch the model in a Session, run the initialized operation
sess = tf.Session()
sess.run(init)



    
# Train for 1000 times!
# batch of 100 at each time
# train_step feeding in the batches data to replace the placeholders
for i in range(10000):


  batch_xs, batch_ys = my_batch(category,100, my_data)
  feed = {x: batch_xs, y_: batch_ys,keep_prob:0.5}

  if i%100 == 0:
#     train_accuracy = accuracy.eval(session=sess, feed_dict=feed)
#     print "type ",tf.shape(accuracy)
#     print "value ",train_accuracy
#     print "step %d, training accuracy %g"%(i, train_accuracy)
    print "Now ",i
  train_step.run(session=sess, feed_dict=feed)


# In[21]:



y <class 'tensorflow.python.framework.ops.Tensor'>
Now  0
Now  100
Now  200
Now  300
Now  400
Now  500
Now  600
Now  700
Now  800
Now  900
Now  1000
Now  1100
Now  1200
Now  1300
Now  1400
Now  1500
Now  1600
Now  1700
Now  1800
Now  1900
Now  2000
Now  2100
Now  2200
Now  2300
Now  2400
Now  2500
Now  2600
Now  2700
Now  2800
Now  2900
Now  3000
Now  3100
Now  3200
Now  3300
Now  3400
Now  3500
Now  3600
Now  3700
Now  3800
Now  3900
Now  4000
Now  4100
Now  4200
Now  4300
Now  4400
Now  4500
Now  4600
Now  4700
Now  4800
Now  4900
Now  5000
Now  5100
Now  5200
Now  5300
Now  5400
Now  5500
Now  5600
Now  5700
Now  5800
Now  5900
Now  6000
Now  6100
Now  6200
Now  6300
Now  6400
Now  6500
Now  6600
Now  6700
Now  6800
Now  6900
Now  7000
Now  7100
Now  7200
Now  7300
Now  7400
Now  7500
Now  7600
Now  7700
Now  7800
Now  7900
Now  8000
Now  8100
Now  8200
Now  8300
Now  8400
Now  8500
Now  8600
Now  8700
Now  8800
Now  8900
Now  9000
Now  9100
Now  9200
Now  9300
Now  9400
Now  9500
N

In [43]:



  
# Merge all the summaries and write them out to /tmp/mnist_logs
merged = tf.merge_summary([weights_summary, biases_summary, y_summary])
writer = tf.train.SummaryWriter("/tmp/read2", sess.graph_def)
tf.train.SummaryWriter("/tmp/read2", sess.graph_def).flush()
# tf.train.SummaryWriter.flush()



In [44]:

# Evaluating
with tf.name_scope("test") as scope:
# evaluation
    y_shaped = tf.reshape(y,[-1])
    y__shaped = tf.reshape(y_,[-1])
    norm1= tf.sqrt(tf.reduce_sum(tf.square(y_shaped),keep_dims=True))
    norm2= tf.sqrt(tf.reduce_sum(tf.square(y__shaped),keep_dims=True))
    dot = tf.reduce_sum(tf.mul(y_shaped,y__shaped))
    cos = abs(dot)/tf.mul(norm1,norm2)
    accuracy = tf.reduce_sum(cos)
#     results = tf.reduce_sum(y__shaped)
 

# get testing data
test_xs,test_ys = testingDataLoader(category,my_testing)


# Train for 1000 times!
# batch of 100 at each time
# train_step feeding in the batches data to replace the placeholders
# for i in range(10000):


#   batch_xs, batch_ys = my_batch(category,100, my_data)
#   feed = {x: batch_xs, y_: batch_ys}

#   if i%100 == 0:
#     train_accuracy = accuracy.eval(session=sess, feed_dict=feed)
#     print "type ",tf.shape(accuracy)
#     print "value ",train_accuracy
#     print "step %d, training accuracy %g"%(i, train_accuracy)
#   train_step.run(session=sess, feed_dict=feed)


#     batch_xs, batch_ys = my_batch(category,100, my_data)
#     feed = {x: batch_xs, y_: batch_ys}
#     sess.run(train_step, feed_dict=feed)




In [45]:
  
    
# test_xs,test_ys = testingDataLoader(category,my_testing)
# Accuracy
print sess.run(accuracy, feed_dict={x: test_xs, y_: test_ys,keep_prob:1.0})




0.445564


In [22]:
# https://github.com/tensorflow/tensorflow/issues/97


In [17]:
# print sess.run(accuracy, feed_dict={x: test_xs, y_: test_ys})
# apply!

# get real data
test_real = realDataLoader(category,my_real)
print test_real

# 
real = tf.placeholder(tf.float32, [None, factor],name="x-test")

with tf.name_scope("apply") as scope:
    results = tf.to_int64(tf.matmul(real, W)+b)
    
    accuracy = results
 
print sess.run(accuracy,feed_dict={real:test_real})


202 5
[[  13.     1.    10.     0.    20.7]
 [  12.     5.     9.     0.     7. ]
 [  19.     4.     5.     0.   689.6]
 ..., 
 [  23.     7.     8.     0.    11.8]
 [  21.     6.     6.     0.     2.7]
 [  22.     1.     9.     0.     6. ]]
[[0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0