In [1]:
import tensorflow as tf
import math
import numpy as np
from numpy import linalg as LA

In [12]:
# sess=tf.InteractiveSession()

tf.set_random_seed(1234)
a = tf.random_uniform([1])
b = tf.random_normal([1])


with tf.Session() as sess1:
    
    print(sess1.run(a))  # generates 'A1'
    print(sess1.run(a))
    a = tf.constant(np.array([[10., 300., .5, .9,],[10., .3, .5, .9,]]))
    b = tf.reshape(a,[-1])
#     sess1.run(b)

#     b = tf.argmax(a,1)
#     b = tf.sigmoid(a)
    print b.eval()


[ 0.9068898]
[ 0.70314264]
[  10.   300.     0.5    0.9   10.     0.3    0.5    0.9]


In [145]:

y = tf.random_normal([8])
y_ = tf.random_uniform([8])
with tf.Session() as sess2:
    print (sess2.run(y))
    print (sess2.run(y_))
    a = tf.constant(np.array([[.1, .3, .5, .9,]]))
    b = tf.sigmoid(a)
    print a.eval()
    print "B",b.eval()
#     print tf.nn.softmax(b).eval()
    print 


[  1.62869835e+00  -1.41275034e-03   8.25094581e-01   9.31116283e-01
  -5.12417972e-01   2.19432545e+00  -1.75402611e-01  -7.35412002e-01]
[ 0.69119942  0.39484012  0.73973382  0.75777209  0.94483304  0.26720428
  0.62430382  0.15760899]
[[ 0.1  0.3  0.5  0.9]]
B [[ 0.52497919  0.57444252  0.62245933  0.7109495 ]]
[[ 0.22949028  0.24112705  0.25298768  0.27639499]]


In [154]:
y = tf.random_normal([2])
y_ = tf.random_uniform([2])


def to_tensor(arg):
  arg = tf.convert_to_tensor(arg, dtype=tf.float32)
  sess=tf.InteractiveSession()
  print arg.eval()
  return arg

with tf.Session() as sess3:
    print (sess3.run(y))
    print (sess3.run(y_))
#     a = y.eval()
#     b = y_.eval()
    print "a",a
#     print b
#     sum = abs(np.dot(a,b))
#     cos = sum/(LA.norm(a)*LA.norm(b))
#     print "norm",math.sqrt(LA.norm(a))
#     print "cos",cos
#     print y.eval()
#     print "cast",tf.cast(tf.equal(y,y_), "float").eval()
#     print type(tf.reduce_mean(tf.cast(tf.equal(y,y_), "float")))
    norm1= tf.sqrt(tf.reduce_sum(tf.square(y),keep_dims=True))
    norm2= tf.sqrt(tf.reduce_sum(tf.square(y_),keep_dims=True))
    dot = tf.reduce_sum(tf.mul(y,y_))
    print "1",norm1.eval()
    print "2",norm2.eval()
    print "dot ",dot.eval()
    cos = abs(dot)/tf.mul(norm1,norm2)
    total = tf.reduce_sum(cos)
    soft = tf.nn.softmax(cos)
    print "cos",cos.eval()
    print "soft",soft.eval()
    print "total",total
#     matrix = tf.reshape(tf.sigmoid(cos),[1,1])
#     print "change", matrix.eval()
#     print tf.sigmoid(cos).eval()
# #     tensor=tf.convert_to_tensor(cos, dtype=tf.float32)
#     soft = tf.nn.softmax(matrix)
#     print soft.eval()
    
#     print tf.cast(,"float")
    
#     print "norm",tf.sqrt(tf.reduce_sum(tf.square(y), 1, keep_dims=True))
    

[ 0.42752936  0.2649377 ]
[ 0.05295765  0.84333658]
a Tensor("Const_19:0", shape=TensorShape([Dimension(1), Dimension(4)]), dtype=float64)
1 [ 0.73670894]
2 [ 0.98080212]
dot  -0.118119


ValueError: Shapes TensorShape([Dimension(1)]) and TensorShape([Dimension(None), Dimension(None)]) must have the same rank

In [135]:
def to_tensor(arg):
  arg = tf.convert_to_tensor(arg, dtype=tf.float32)
  sess=tf.InteractiveSession()
  print arg.eval()
  return arg




me = to_tensor(0.3)
print "type",type(me)
print "shape",tf.shape(me)
print "shape",tf.shape(me)

0.3
type <class 'tensorflow.python.framework.ops.Tensor'>
shape Tensor("Shape_16:0", shape=TensorShape([Dimension(0)]), dtype=int32)
shape Tensor("Shape_17:0", shape=TensorShape([Dimension(0)]), dtype=int32)
